
resolver 127.0.0.11 valid=10s ipv6=off;

log_format upstreamlog '$remote_addr - [$time_local] "$request" '
                       'upstream: $upstream_addr';
server {
    listen 80;
    server_name localhost;
    access_log /var/log/nginx/access.log upstreamlog;


    location / {
        set $upstream api;
        proxy_pass http://$upstream:3000;
       
    }
}